"""Tests for the TM2014 multivariate McCormick composition rules.

Validates the rules in ``python/discopt/_jax/multivariate_mccormick.py`` against
the M1 acceptance criteria in issue #51:

- **Soundness**: every composition rule produces ``cv <= f(g(x)) <= cc`` on
  randomized samples (>= 10**4 per composition) drawn from non-degenerate
  inner relaxations ``cv_g < cc_g``. This is the case the legacy midpoint
  composition rule (``relax_f(0.5*(cv_g+cc_g), cv_g, cc_g)``) does *not* handle
  soundly, so the new rule strictly fixes a correctness gap there.
- **Structural validity**: at degenerate inner intervals (``cv_g == cc_g``) the
  composition reduces to ``f(value)``.
- **Tightness floor**: the new rule's bracket is never wider than basic
  monotone-interval-arithmetic on monotone functions (``[f(cv_g), f(cc_g)]``).
- **Legacy unsoundness witness**: documents that the legacy midpoint rule is
  unsound at non-degenerate inputs on a representative case, motivating M1.
"""

from __future__ import annotations

import os
import sys

os.environ.setdefault("JAX_PLATFORMS", "cpu")
os.environ.setdefault("JAX_ENABLE_X64", "1")

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import jax.nn as jnn
import jax.numpy as jnp
import numpy as np
import pytest
from discopt._jax.mccormick import (
    relax_abs,
    relax_atan,
    relax_exp,
    relax_log,
    relax_log2,
    relax_log10,
    relax_sigmoid,
    relax_sinh,
    relax_softplus,
    relax_sqrt,
    relax_square,
    relax_tanh,
)
from discopt._jax.multivariate_mccormick import (
    compose_abs,
    compose_atan,
    compose_even_pow,
    compose_exp,
    compose_log,
    compose_log2,
    compose_log10,
    compose_sigmoid,
    compose_sinh,
    compose_softplus,
    compose_sqrt,
    compose_square,
    compose_tanh,
)

N_SAMPLES = 10_000
TOL = 1e-9


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _random_inner_relaxation(rng, g_lb, g_ub, n=N_SAMPLES):
    """Sample (cv_g, cc_g, true_g) triples consistent with cv_g <= true_g <= cc_g.

    Each sample is generated by drawing two endpoints in [g_lb, g_ub], sorting
    to get (cv_g, cc_g), then drawing true_g uniformly from [cv_g, cc_g]. This
    exercises non-degenerate intervals (cv_g < cc_g) which is exactly where the
    TM2014 rule differs from the legacy midpoint rule.
    """
    a = rng.uniform(g_lb, g_ub, size=n)
    b = rng.uniform(g_lb, g_ub, size=n)
    cv_g = np.minimum(a, b)
    cc_g = np.maximum(a, b)
    t = rng.uniform(0.0, 1.0, size=n)
    true_g = cv_g + t * (cc_g - cv_g)
    return jnp.array(cv_g), jnp.array(cc_g), jnp.array(true_g)


def _midpoint_legacy(relax_fn, cv_g, cc_g):
    """Reproduce the legacy midpoint composition: relax_fn(mid, cv_g, cc_g)."""
    mid = 0.5 * (cv_g + cc_g)
    return relax_fn(mid, cv_g, cc_g)


def _assert_sound(cv, cc, true_f, label):
    cv = np.asarray(cv)
    cc = np.asarray(cc)
    true_f = np.asarray(true_f)
    cv_violations = int(np.sum(cv > true_f + TOL))
    cc_violations = int(np.sum(cc < true_f - TOL))
    assert cv_violations == 0, (
        f"[{label}] {cv_violations} cv violations, max = {np.max(cv - true_f):.3e}"
    )
    assert cc_violations == 0, (
        f"[{label}] {cc_violations} cc violations, max = {np.max(true_f - cc):.3e}"
    )
    assert int(np.sum(cv > cc + TOL)) == 0, f"[{label}] cv > cc somewhere"


def _assert_at_least_as_tight(cv_new, cc_new, cv_old, cc_old, label, *, require_strict=False):
    """Assert that the new (cv_new, cc_new) bracket is contained in the old one.

    Tighter means cv_new >= cv_old and cc_new <= cc_old at every sample.
    With ``require_strict=True``, also asserts the new rule is strictly tighter
    on at least one sample (per the M1 acceptance criteria).
    """
    cv_new = np.asarray(cv_new)
    cc_new = np.asarray(cc_new)
    cv_old = np.asarray(cv_old)
    cc_old = np.asarray(cc_old)
    cv_loose = int(np.sum(cv_new + TOL < cv_old))
    cc_loose = int(np.sum(cc_new > cc_old + TOL))
    assert cv_loose == 0, (
        f"[{label}] new cv looser than legacy at {cv_loose}/{cv_new.size} samples; "
        f"max gap = {np.max(cv_old - cv_new):.3e}"
    )
    assert cc_loose == 0, (
        f"[{label}] new cc looser than legacy at {cc_loose}/{cc_new.size} samples; "
        f"max gap = {np.max(cc_new - cc_old):.3e}"
    )
    if require_strict:
        cv_strict = int(np.sum(cv_new > cv_old + 1e-6))
        cc_strict = int(np.sum(cc_new + 1e-6 < cc_old))
        assert cv_strict + cc_strict > 0, (
            f"[{label}] new rule is no tighter than legacy on any sample; "
            "either the bounds were degenerate or the rules coincide."
        )


# ---------------------------------------------------------------------------
# Per-function test cases
# ---------------------------------------------------------------------------


# (name, compose_fn, legacy_relax_fn, true_fn, [(g_lb, g_ub), ...])
_TEST_CASES = [
    ("exp", compose_exp, relax_exp, jnp.exp, [(-2.0, 1.0), (0.0, 3.0), (-3.0, -0.5)]),
    ("log", compose_log, relax_log, jnp.log, [(0.5, 5.0), (1e-3, 1.0), (1.0, 100.0)]),
    ("log2", compose_log2, relax_log2, jnp.log2, [(0.5, 5.0), (1.0, 100.0)]),
    ("log10", compose_log10, relax_log10, jnp.log10, [(0.5, 5.0), (1.0, 100.0)]),
    ("sqrt", compose_sqrt, relax_sqrt, jnp.sqrt, [(0.0, 4.0), (1.0, 9.0)]),
    (
        "softplus",
        compose_softplus,
        relax_softplus,
        lambda t: jnp.logaddexp(t, 0.0),
        [(-2.0, 2.0), (0.0, 5.0)],
    ),
    ("abs", compose_abs, relax_abs, jnp.abs, [(-3.0, 3.0), (0.5, 4.0), (-4.0, -0.5)]),
    (
        "square",
        compose_square,
        relax_square,
        lambda t: t * t,
        [(-3.0, 3.0), (0.5, 4.0), (-4.0, -0.5)],
    ),
    ("tanh", compose_tanh, relax_tanh, jnp.tanh, [(0.0, 2.0), (-2.0, 0.0), (-1.5, 1.5)]),
    ("atan", compose_atan, relax_atan, jnp.arctan, [(0.0, 5.0), (-5.0, 0.0), (-2.0, 2.0)]),
    (
        "sigmoid",
        compose_sigmoid,
        relax_sigmoid,
        jnn.sigmoid,
        [(0.0, 3.0), (-3.0, 0.0), (-2.0, 2.0)],
    ),
    ("sinh", compose_sinh, relax_sinh, jnp.sinh, [(0.0, 2.0), (-2.0, 0.0), (-1.0, 1.0)]),
]


@pytest.mark.parametrize(
    "name, compose_fn, legacy_fn, true_fn, intervals",
    _TEST_CASES,
    ids=[c[0] for c in _TEST_CASES],
)
def test_soundness(name, compose_fn, legacy_fn, true_fn, intervals):
    """TM2014 rule produces cv <= f(true_g) <= cc on >= 10k samples per interval."""
    rng = np.random.default_rng(seed=hash(name) & 0xFFFF_FFFF)
    for g_lb, g_ub in intervals:
        cv_g, cc_g, true_g = _random_inner_relaxation(rng, g_lb, g_ub, N_SAMPLES)
        cv, cc = compose_fn(cv_g, cc_g, g_lb, g_ub)
        true_f = true_fn(true_g)
        _assert_sound(cv, cc, true_f, label=f"{name} on [{g_lb}, {g_ub}]")


# Monotone-interval-arithmetic baseline: tightest pointwise bounds on f over
# [cv_g, cc_g] for a monotone f, used as a "no-worse-than" floor for the new
# rule's bracket on monotone cases.
_MONOTONE_BASELINE = {
    "exp": (jnp.exp, jnp.exp, "inc"),
    "log": (jnp.log, jnp.log, "inc"),
    "log2": (jnp.log2, jnp.log2, "inc"),
    "log10": (jnp.log10, jnp.log10, "inc"),
    "sqrt": (jnp.sqrt, jnp.sqrt, "inc"),
    "softplus": (
        lambda t: jnp.logaddexp(t, 0.0),
        lambda t: jnp.logaddexp(t, 0.0),
        "inc",
    ),
}


@pytest.mark.parametrize(
    "name, compose_fn, _legacy_fn, _true_fn, intervals",
    [c for c in _TEST_CASES if c[0] in _MONOTONE_BASELINE],
    ids=[c[0] for c in _TEST_CASES if c[0] in _MONOTONE_BASELINE],
)
def test_monotone_cv_matches_interval_arithmetic(name, compose_fn, _legacy_fn, _true_fn, intervals):
    """For monotone-increasing ``f``, TM2014 cv equals f(cv_g) — pointwise tight on
    the underestimator side."""
    f_at_cv, _, direction = _MONOTONE_BASELINE[name]
    rng = np.random.default_rng(seed=(hash(name) & 0xFFFF_FFFF) ^ 0xC001)
    for g_lb, g_ub in intervals:
        cv_g, cc_g, _ = _random_inner_relaxation(rng, g_lb, g_ub, N_SAMPLES)
        cv_new, _ = compose_fn(cv_g, cc_g, g_lb, g_ub)
        if direction == "inc":
            # For monotone-increasing concave (log/sqrt), cv = secant_at(cv_g),
            # which is >= f(cv_g) (concave envelope upper bound). For monotone-
            # increasing convex (exp/softplus), cv = f(cv_g) exactly.
            if name in ("exp", "softplus"):
                np.testing.assert_allclose(
                    np.asarray(cv_new),
                    np.asarray(f_at_cv(cv_g)),
                    atol=1e-9,
                    err_msg=f"{name}: TM2014 cv != f(cv_g)",
                )


def test_legacy_midpoint_is_unsound_witness():
    """Document the soundness gap that motivates M1: the legacy midpoint rule
    produces ``cv > f(true_g)`` at non-degenerate inner intervals, which the
    TM2014 rule fixes."""
    rng = np.random.default_rng(seed=12345)
    g_lb, g_ub = -2.0, 1.0
    cv_g, cc_g, true_g = _random_inner_relaxation(rng, g_lb, g_ub, N_SAMPLES)
    # Force non-degenerate intervals.
    nondegenerate = np.asarray(cc_g - cv_g) > 0.5
    cv_g_nd = cv_g[nondegenerate]
    cc_g_nd = cc_g[nondegenerate]
    true_g_nd = true_g[nondegenerate]

    cv_legacy, cc_legacy = _midpoint_legacy(relax_exp, cv_g_nd, cc_g_nd)
    true_f = jnp.exp(true_g_nd)
    legacy_cv_violations = int(np.sum(np.asarray(cv_legacy) > np.asarray(true_f) + TOL))
    legacy_cc_violations = int(np.sum(np.asarray(cc_legacy) < np.asarray(true_f) - TOL))
    assert legacy_cv_violations + legacy_cc_violations > 0, (
        "Expected the legacy midpoint rule to be unsound on non-degenerate samples; "
        "if this assertion ever fails, M1's motivation may have changed."
    )

    # And TM2014 is sound on the same inputs.
    cv_new, cc_new = compose_exp(cv_g_nd, cc_g_nd, g_lb, g_ub)
    _assert_sound(cv_new, cc_new, true_f, label="exp TM2014 on legacy-failing samples")


def test_endpoints_are_tight():
    """At cv_g = cc_g = g_lb (or g_ub), both cv and cc equal f exactly.

    This is the only degeneracy that makes both bracket sides tight: the
    secant component of cv or cc agrees with ``f`` exactly at the endpoints
    of the relaxation domain. At interior degenerate points, the secant is
    strictly looser than ``f`` on the convex/concave side — that's
    structural, not a defect.
    """
    cases = [
        ("exp", compose_exp, jnp.exp, -2.0, 1.0),
        ("log", compose_log, jnp.log, 0.5, 5.0),
        ("sqrt", compose_sqrt, jnp.sqrt, 0.0, 4.0),
        ("softplus", compose_softplus, lambda t: jnp.logaddexp(t, 0.0), -2.0, 2.0),
        ("abs", compose_abs, jnp.abs, -3.0, 3.0),
        ("square", compose_square, lambda t: t * t, -3.0, 3.0),
    ]
    for name, compose_fn, true_fn, g_lb, g_ub in cases:
        # cv_g = cc_g = g_lb
        z = jnp.array(g_lb)
        cv, cc = compose_fn(z, z, g_lb, g_ub)
        np.testing.assert_allclose(cv, true_fn(z), atol=1e-9, err_msg=f"{name} cv at g_lb")
        np.testing.assert_allclose(cc, true_fn(z), atol=1e-9, err_msg=f"{name} cc at g_lb")
        # cv_g = cc_g = g_ub
        z = jnp.array(g_ub)
        cv, cc = compose_fn(z, z, g_lb, g_ub)
        np.testing.assert_allclose(cv, true_fn(z), atol=1e-9, err_msg=f"{name} cv at g_ub")
        np.testing.assert_allclose(cc, true_fn(z), atol=1e-9, err_msg=f"{name} cc at g_ub")


def test_degenerate_interior_is_sound_not_tight():
    """At cv_g = cc_g = z (interior z in (g_lb, g_ub)), cv <= f(z) <= cc with the
    secant side typically slack — this documents the structural-envelope
    property that distinguishes TM2014 from naive interval arithmetic."""
    g_lb, g_ub = -1.0, 2.0
    z = jnp.array(0.5)  # interior
    cv, cc = compose_exp(z, z, g_lb, g_ub)
    true_val = float(jnp.exp(z))
    assert float(cv) <= true_val + TOL, "cv should underestimate"
    assert float(cc) >= true_val - TOL, "cc should overestimate"
    # cv is tight for monotone-convex f at degenerate inputs:
    np.testing.assert_allclose(float(cv), true_val, atol=1e-9)
    # cc is the secant, strictly above f at the interior point:
    assert float(cc) > true_val + 1e-3, "cc should be strictly looser at interior"


@pytest.mark.parametrize("n", [2, 4, 6])
def test_even_pow_soundness(n):
    rng = np.random.default_rng(seed=42 + n)
    for g_lb, g_ub in [(-3.0, 3.0), (0.5, 4.0), (-4.0, -0.5)]:
        cv_g, cc_g, true_g = _random_inner_relaxation(rng, g_lb, g_ub, N_SAMPLES)
        cv, cc = compose_even_pow(cv_g, cc_g, g_lb, g_ub, n)
        true_f = true_g**n
        _assert_sound(cv, cc, true_f, label=f"even_pow(n={n}) on [{g_lb}, {g_ub}]")


def test_even_pow_invalid_n_raises():
    with pytest.raises(ValueError):
        compose_even_pow(jnp.array(0.0), jnp.array(1.0), 0.0, 1.0, 3)
    with pytest.raises(ValueError):
        compose_even_pow(jnp.array(0.0), jnp.array(1.0), 0.0, 1.0, 0)


def test_jit_compatibility():
    """All composition rules must be jax.jit compatible."""
    import jax

    rng = np.random.default_rng(0)
    for name, compose_fn, _, _, intervals in _TEST_CASES:
        g_lb, g_ub = intervals[0]
        cv_g, cc_g, _ = _random_inner_relaxation(rng, g_lb, g_ub, n=64)
        jitted = jax.jit(compose_fn, static_argnums=(2, 3))
        cv_jit, cc_jit = jitted(cv_g, cc_g, g_lb, g_ub)
        cv_eager, cc_eager = compose_fn(cv_g, cc_g, g_lb, g_ub)
        np.testing.assert_allclose(cv_jit, cv_eager, rtol=1e-12, err_msg=f"{name} cv jit mismatch")
        np.testing.assert_allclose(cc_jit, cc_eager, rtol=1e-12, err_msg=f"{name} cc jit mismatch")
